/*
  Group Number 53
  Snehal Juneja: 2019B2A70994P
  Aryan Gautam Nadkarni: 2019B3A70406P
  Ishan Rai: 2019B3A70504P
  Shrey Bansal: 2019B3A70592P
  Karizma Khurana: 2019B4A70708P
*/
#include <time.h>
#include "parser.h"
#include "lexer.h"
#include "parserDef.h"

extern int initializedOnce;
int main(int argc, char *argv[])
{

    char *nameOfTheTestFile = argv[1];
    //printf("%s\n",nameOfTheTestFile);
    char *parseTree = argv[2];
    //printf("%s\n",parseTree);
    int sizeOfBuffer = atoi(argv[3]); // changes size of buffer
    //printf("%d\n",sizeOfBuffer);
    int inputFromTheUser;
    printf("FIRST and FOLLOW set automated\n");
    printf("Both lexical and syntax analysis modules implemented\n");
    printf("Modules compile successfully\n");
    printf("Modules work with all the test cases\n");
    printf("Parse Tree Constructed\n\n");
    
    initializedOnce = 0;
    while (1)
    {
        printf("OPTIONS:-\n0: FOR EXIT\n1: FOR REMOVAL OF COMMENTS\n2: FOR PRINTING THE TOKEN LIST GENERATED BY THE LEXER\n3: FOR PARSING TO VERIFY THE SYNTACTIC CORRECTNESS OF THE INPUT SOURCE CODE AND PRINTING THE PARSE TREE\n4: FOR PRINTING THE TOTAL TIME TAKEN\n");
        printf("Please enter an approporiate option: ");
        scanf("%d", &inputFromTheUser);
        FILE* fptr = fopen(nameOfTheTestFile,"r");
        if(fptr==NULL){
            printf("Error in opening file\n");
            printf("Exiting program. Try again!");
            exit(0);
        }
        // initialize this with the name of the test.txt file
        char *theCleanCodeWithoutComments = "cleanCode.txt"; // intialize this with the name of the clean.txt file
        switch (inputFromTheUser)
        {
        case 0:
            exit(0);
            break;
        case 1:
            removeComments(nameOfTheTestFile, theCleanCodeWithoutComments);
            break;
        case 2:
        {
            //FILE* fptr = fopen(nameOfTheTestFile,"r");
            //rewind(fptr);
            initializeLexer(fptr,sizeOfBuffer);
            struct tokenInfo temp = getNextToken();
            while (temp.token != TK_ENDOFFILE)
            {
                if (temp.token != TK_IGNORE && temp.token != TK_NUM && temp.token != TK_RNUM)
                {
                    printf("%d %s ", temp.lineNo, temp.lexeme);
                    printTokenName(temp.token);
                    printf("\n");
                }
                else if (temp.token == TK_NUM)
                {
                    printf("%d %d ", temp.lineNo, *(int *)temp.value);
                    printTokenName(temp.token);
                    printf("\n");
                }
                else if (temp.token == TK_RNUM)
                {
                    printf("%d %f ", temp.lineNo, *(float *)temp.value);
                    printTokenName(temp.token);
                    printf("\n");
                }
                if (temp.token == TK_LEX_ERROR)
                {
                    printf("ERROR IN LINE NUMBER: %d\n", temp.lineNo);
                    printf("THE LEXEME CORRESPONDING TO THE ERROR: %s\n", temp.lexeme);
                }
                temp = getNextToken();
            }
            freeBuffers();
            //fclose(fptr);
            break;
        }
        case 3:
        {
            //initializeLexer(nameOfTheTestFile);
            //FILE* fptr = fopen(nameOfTheTestFile,"r");
            //rewind(fptr);
            TREE_NODE tree = initializeParser(fptr,sizeOfBuffer);
            freeBuffers();
            //freeParser();
            //fclose(fptr);
            FILE* fp = fopen(parseTree,"w");
            printParseTree(tree, fp);
            fclose(fp);
            break;
        }
        case 4:
        {
            clock_t start_time, end_time;
            double total_CPU_time, total_CPU_time_in_seconds;
            start_time = clock();
            // invoke
            //FILE* fptr = fopen(nameOfTheTestFile,"r");

            TREE_NODE rootOfTheTree = initializeParser(fptr,sizeOfBuffer);
            //freeParser();
            //fclose(fptr);
            end_time = clock();
            total_CPU_time = (double)(end_time - start_time);
            total_CPU_time_in_seconds = total_CPU_time / CLOCKS_PER_SEC;
            printf("Total CPU time: %f\n", total_CPU_time);
            printf("Total CPU time in seconds: %f\n", total_CPU_time_in_seconds);
            break;
        }
    default : {
        printf("Enter valid option\n");
        }
    }
    fclose(fptr);
    }
    
}